### ISSUE TITLE
Partition layout not detected. Aborting bootstrap

### ISSUE THREAD

**Issue by Coll147** [holoiso-staging/issuetracker#24]
I am getting the following error when trying to install HoloISO 1.1.6 (1.1.6/main) > holoiso_beta_snapshot20240325.1158.39-InstallerBuild-20240326142912-x86_64.iso
![image](https://github.com/HoloISO/issuetracker/assets/91793263/d3cb7abb-eb1f-49a8-9e8c-5f48bb707873)

**Comment by DontTouchMyHentai** [comment]
Im too suffering from this problem. Im on the beta as well.

**Comment by theVakhovskeIsTaken** [comment]
Fixed. The installer fix will roll out today

**Comment by Coll147** [comment]
> Fixed. The installer fix will roll out today

I have tried running the Holoiso ISO and replacing the installation files with the latest ones from [this repository](https://github.com/HoloISO/holoiso-installer), but I still have the same error.

**Comment by FantasyGmm** [comment]
Because the VFAT label is in uppercase, you need to modify `/usr/bin/holoiso_bootstrap` to replace `holo_efi` with `HOLO_EFI` so that the installation can proceed.
